# Declares AWS as the infrastructure provider
provider "aws" {
  region = "us-east-2" # Sets the AWS region to Ohio

  # Defines tags that will be automatically applied to all supported resources
  default_tags {
    tags = {
      hashicorp-learn = "aws-asg" # Assigns a tracking tag for this tutorial configuration
    }
  }
}

# Dynamically fetches a list of available AWS Availability Zones in us-east-2
data "aws_availability_zones" "available" {
  state = "available" # Filters the query to only return zones that are currently active
}

# Calls a verified external registry module to provision a standardized network setup
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws" # The source path of the AWS VPC module on the Terraform Registry
  version = "2.77.0"                      # Locks the module to a specific version for architectural stability

  name = "main-vpc" # Names the created VPC resource
  cidr = "10.0.0.0/16" # Defines the primary private IP range for the entire network

  azs                  = data.aws_availability_zones.available.names # Spreads the subnets across the active AZs fetched above
  public_subnets       = ["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"] # Allocates three distinct public IP ranges inside the AZs
  enable_dns_hostnames = true # Automatically assigns public DNS hostnames to instances running in this VPC
  enable_dns_support   = true # Enables the native AWS DNS resolution service for this VPC
}

# Dynamically searches for an official Amazon Machine Image (AMI) to use for the servers
data "aws_ami" "amazon_linux" {
  most_recent = true # If multiple images match the filter, always grab the newest one
  owners      = ["amazon"]  # Restricts the search specifically to images published by Amazon

  # Filters the AMI catalog down to a specific Operating System type
  filter {
    name   = "name" # Filters based on the AMI name string
    values = ["amzn2-ami-hvm-*-x86_64-ebs"]  # Wildcard pattern to match 64-bit Amazon Linux 2 AMIs
  }
}

# Defines the legacy template configuration for spawning new EC2 instances
resource "aws_launch_configuration" "terratutorial" {
  name_prefix     = "learn-terraform-aws-asg-" # Prefixes the unique generated name for this configuration
  image_id        = data.aws_ami.amazon_linux.id  # Dynamically passes the ID of the Amazon Linux 2 AMI found above
  instance_type   = "t2.micro" # Specifies the hardware size (1 vCPU, 1 GB RAM—Eligible for Free Tier)
}

# Defines the rules and scaling boundaries for a cluster of self-healing EC2 instances
resource "aws_autoscaling_group" "terratutorial" {
  name                 = "terratutorial" # The deployment name of the Auto Scaling Group
  min_size             = 1 # Absolute minimum number of EC2 instances that must be kept alive
  max_size             = 3 # Maximum limit of EC2 instances allowed during high-traffic spikes
  desired_capacity     = 1 # The base number of instances to spin up immediately on initial deployment
  launch_configuration = aws_launch_configuration.terratutorial.name # Instructs the group to build instances using the blueprint above
  vpc_zone_identifier  = module.vpc.public_subnets # Places the instances into the public subnets generated by the VPC module

  health_check_type    = "ELB" # Uses the Load Balancer's target checks (instead of just EC2 pings) to decide if a server is dead

  # Defines a resource tag that will be assigned to every EC2 instance spawned by this group
  tag {
    key                 = "Name" # The tag key
    value               = "Learn ASG - terratutorial" # The tag value
    propagate_at_launch = true # Evaluates to true so that instances inherit this tag automatically when scaled up
  }
}

# Defines a policy that dictates exactly how the Auto Scaling Group should shrink
resource "aws_autoscaling_policy" "scale_down" {
  name                   = "terratutorial-scale-down" # The policy name
  scaling_adjustment     = -1 # Tells the group to subtract exactly one instance when executed
  adjustment_type        = "ChangeInCapacity" # Specifies that the adjustment represents a flat number change
  cooldown               = 120 # Gives the group a 120-second rest period before it can scale down again
  autoscaling_group_name = aws_autoscaling_group.terratutorial.name # Binds
